<?php

########################################################################
# Extension Manager/Repository config file for ext: "in2snippets"
#
# Auto generated by Extension Builder 2011-08-23
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'in2snippets',
	'description' => 'A little extension for adding and searching/filtering Code-Snippets.',
	'category' => 'plugin',
	'author' => 'David Richter',
	'author_email' => 'david.richter@in2code.de',
	'author_company' => 'in2code',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.8',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'typo3' => '4.5.0-0.0.0',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>